### ISSUE TITLE
En Google Chrome no Funciona

### ISSUE THREAD

**Issue by quinterol** [zalazarc20/Mundial2022#3]
Hola, que genial estaa esto, pero por algun motivo cuando lo abro en Google Chrome no me carga ninguno, pero usando Firefox todo va perfecto.

Saben porque podria ser esto? y como podria solucionarlo.

Esta corriendo en una maquina debian, usando python como servidor http.

Gracias. :smile:

**Comment by quinterol** [comment]
> > Hola, que genial estaa esto, pero por algun motivo cuando lo abro en Google Chrome no me carga ninguno, pero usando Firefox todo va perfecto.
> > 
> > Saben porque podria ser esto? y como podria solucionarlo.
> > 
> > Esta corriendo en una maquina debian, usando python como servidor http.
> > 
> > Gracias. 😄
> 
> Puede que tu google chrome este desactualizado? 🤔
> En mi caso tengo windows y en chrome me anda perfecto 🤔 pero voy a comprobar por las dudas. Gracias por avisar

Pues estoy usando, la versión 108.0.5359.71 lo probé en una máquina con Linux y una con Windows en ambas no funcionaba pero con Firefox todo 👌

**Comment by mclitos** [comment]
hola TVPublica parece que no esta trabajando , los demas estan OK

**Comment by zalazarc20** [comment]
Hola, hay veces que los enlaces dejan de funcionar y se arreglan solos. Por lo general para el Mundial funcionan todos ok 😎
