### ISSUE TITLE
Publish web server to easily use

### ISSUE THREAD

**Issue by vgpastor** [zalazarc20/Mundial2022#5]
Hola!

Si publicas el repo en modo páginas o con GIST, no obligaras a la gente a montarse servidor para reproducirlo

Te dejo algo de documentación https://pages.github.com/  https://htmlpreview.github.io/

**Comment by zalazarc20** [comment]
> Hola!
> 
> Si publicas el repo en modo páginas o con GIST, no obligaras a la gente a montarse servidor para reproducirlo
> 
> Te dejo algo de documentación https://pages.github.com/ https://htmlpreview.github.io/

Gracias por tu comentario 😊
El problema es que al subirlo a un hosting o github pages, para poder acceder al repo se le agrega un sub-dominio, y la app al tener un dominio o sub-dominio no carga los canales, al parecer se bloquean
