### ISSUE TITLE
Links de streams caidos?

### ISSUE THREAD

**Issue by nachovizzo** [zalazarc20/Mundial2022#6]
![image](https://user-images.githubusercontent.com/21349875/206583132-fb761d06-384b-437b-bfe1-92a1a40ef4e5.png)

Hola, muy buena la app!. Hay alguna manera de ver porque esto no funciona? Estoy fuera de Argentina pero conectado a una VPN

Gracias

**Comment by zalazarc20** [comment]
> ![image](https://user-images.githubusercontent.com/21349875/206583132-fb761d06-384b-437b-bfe1-92a1a40ef4e5.png)
> 
> Hola, muy buena la app!. Hay alguna manera de ver porque esto no funciona? Estoy fuera de Argentina pero conectado a una VPN
> 
> Gracias

Hola 😎 la VPN tiene que ser de Argentina para que funcione <br> Si vas a usar la App en pc te recomiendo está extension [Urban VPN](https://chrome.google.com/webstore/detail/urban-vpn-proxy/eppiocemhmnlbhjplcgkofciiegomcon?hl=es)

**Comment by nachovizzo** [comment]
Estoy conectado a una VPN de argentina, me podras confirmar si funciona? como para saber si el problema es la VPN. 

Ahi probé con Urban VPN y tampoco me anduvo

**Comment by zalazarc20** [comment]
> Estoy conectado a una VPN de argentina, me podras confirmar si funciona? como para saber si el problema es la VPN.
> 
> Ahi probé con Urban VPN y tampoco me anduvo

Te pregunto, donde estás ubicado? 🤔 
Capas puedas tener acceso a otros canales, dependiendo el país donde te encuentres

Y sino, te recomiendo la página [futbol para todos](https://futbolparatodos.online/es/mundial-ch2/) y decime si te carga algun canal 🤔
