### ISSUE TITLE
TVPublica no conecta

### ISSUE THREAD

**Issue by mclitos** [zalazarc20/Mundial2022#7]
hola , gracias por el script , el canal TVpublica se encuentra caido no se si el CK ( o link) cambio para esta semana 

![image](https://user-images.githubusercontent.com/54686138/206750767-bd912d60-fde5-45af-a4fb-1f5854cddf41.png)

**Comment by mclitos** [comment]
si , por si la dudas lo acabo de hacer de nuevo he igual , puede que tenga geo bloqueo :(

**Comment by zalazarc20** [comment]
> si , por si la dudas lo acabo de hacer de nuevo he igual , puede que tenga geo bloqueo :(

No te preocupes 🤔 podes usar las otras opciones 😎
Ahora si ningun canal te funciona, te recomiendo la pagina de [futbol para todos](https://futbolparatodos.online/es/)
